### ISSUE TITLE
implement ux changes

### ISSUE THREAD

**Issue by pepem00n** [pepemon-dao/pepemon-frontend#39]
Please implement the UX feedback from:

[Pepemon_Feedback__nov_14_compressed_1.pdf](https://github.com/pepem00n/pepemon-frontend/files/8890063/Pepemon_Feedback__nov_14_compressed_1.pdf)

**Comment by drikusroor** [comment]
With regards to the shadow on the cards on **2. Homepage** (see image), apparently the images are not cropped correctly, making it hard to render a shadow using CSS. Currently, the shadow is basically baked into the image, which then gets ugly after compression. Does anyone have nice cropped versions of these cards?

<img width="1267" alt="afbeelding" src="https://user-images.githubusercontent.com/8208970/173446578-ea836892-191f-47cd-a3fa-cc64fc3b1d45.png">

**Comment by drikusroor** [comment]
@pepem00n see image. Currently this menu is a single select, should this become a multi select?

<img width="1239" alt="afbeelding" src="https://user-images.githubusercontent.com/8208970/176776963-4119f619-6b44-413b-9c92-5b21fd6173ed.png">
